# Generated by Django 5.2.8 on 2025-12-28 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_title_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_tag',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=120, null=True),
        ),
    ]
