# Generated by Django 5.2.8 on 2025-12-29 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_title_alter_post_title_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, choices=[('General', '일반'), ('Hobby', '취미'), ('Music', '음악'), ('Movie', '영화'), ('Game', '게임'), ('Sports', '스포츠')], default='General', max_length=50, null=True),
        ),
    ]
