# Generated by Django 5.2.8 on 2025-12-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, choices=[('General', '일반'), ('Hobby', '취미'), ('Music', '음악'), ('Movie', '영화'), ('Game', '게임'), ('coding', '코딩'), ('Politics', '정치'), ('Science', '과학'), ('Travel', '여행'), ('Food', '음식'), ('Sports', '스포츠')], default='General', max_length=50, null=True),
        ),
    ]
