# Generated by Django 5.2.8 on 2025-12-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_category_question_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ManyToManyField(blank=True, to='polls.category'),
        ),
    ]
