# Generated by Django 5.2.8 on 2026-01-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_question_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(blank=True, help_text='답변을 입력하세요.', max_length=200, null=True, verbose_name='답변'),
        ),
    ]
