--
-- PostgreSQL database dump
--

\restrict Ta5Kj6NURYEF0chFrSvACaQPvtlue0skWS5M8uG1W6XWFlOyRresmkXAhNmuj3K

-- Dumped from database version 17.7
-- Dumped by pg_dump version 17.7

-- Started on 2026-01-01 10:27:36

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 236 (class 1259 OID 77943)
-- Name: blog_post; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.blog_post (
    id bigint NOT NULL,
    title character varying(100) NOT NULL,
    content text NOT NULL,
    date_posted timestamp with time zone NOT NULL,
    author_id integer NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    title_tag character varying(120),
    category_id bigint
);


ALTER TABLE public.blog_post OWNER TO postgres;

--
-- TOC entry 235 (class 1259 OID 77942)
-- Name: blog_post_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.blog_post ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.blog_post_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 5092 (class 0 OID 77943)
-- Dependencies: 236
-- Data for Name: blog_post; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.blog_post (id, title, content, date_posted, author_id, updated_at, title_tag, category_id) FROM stdin;
104	리트머스	땡 히드라에 끝	2019-03-19 00:00:00+09	3	2026-01-01 08:58:37.542891+09	리트머스	8
13	뭐야	애드벌룬이 뭐지?	2015-04-08 00:00:00+09	45	2025-12-28 15:26:37.208563+09	\N	\N
646	form과 내용 토글하기 javascript 필요	보여줄 내용과 폼을 생성\r\njavascript에서 내용과 폼을 토글\r\njs function argument로 comment id를 넣어주고\r\ngetElementById에서 이 id를 이용해서 찾아야하고, \r\n엘리먼트 id도 이 id를 이용해서 지정해 주고 내용도 넣어주어야함\r\n&lt;div id="comment-content-{{ comment.id }}">\r\n  &lt;p>{{ comment.content|safe }}</p>\r\n  &lt;/div>\r\n<br>\r\n    function toggleEdit(commentId) {<br>\r\n        const contentDiv = document.getElementById(`comment-content-${commentId}`);<br>\r\n        const editDiv = document.getElementById(`comment-edit-${commentId}`);<br>\r\n        if (editDiv.style.display === 'none') {<br>\r\n            editDiv.style.display = 'block';<br>\r\n            contentDiv.style.display = 'none';<br>\r\n        } else {<br>\r\n            editDiv.style.display = 'none';<br>\r\n            contentDiv.style.display = 'block';<br>\r\n        }<br>\r\n    }	2012-02-09 00:00:00+09	1	2026-01-01 09:12:24.625224+09	form과-내용-토글하기-javascript-필요	5
63	2024 시즌3	현재-1.1 시청중임	2010-10-20 00:00:00+09	2	2026-01-01 09:37:47.950446+09	시청중	8
64	이재호 싫어요	데란 싫어요	2015-03-23 00:00:00+09	1	2025-12-28 15:22:48.146159+09	\N	\N
249	아이브 안유지	브로그 포스트	2024-03-29 00:00:00+09	93	2026-01-01 08:40:24.771042+09	아이브-안유지	3
121	Fairhaven	Fusce consequat. Nulla nisl. Nunc nisl.\n\nDuis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.\n\nIn hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.	2011-03-13 00:00:00+09	54	2025-12-28 14:41:25.34567+09	\N	\N
223	새해-2026	안녕 ~~~~	2025-05-22 00:00:00+09	12	2026-01-01 08:41:53.955423+09	새해-2026	1
254	이겨야 하는데	3시 마비됐습니다.	2018-06-01 00:00:00+09	1	2025-12-31 15:52:28.178156+09	이겨야-하는데	8
274	메탈리카	음악 입니다.	2009-10-29 00:00:00+09	2	2025-12-31 16:06:02.694301+09	메탈리카	3
322	아이브 리더	가을  레이  장원영  리즈  이서	2017-01-18 00:00:00+09	81	2025-12-31 16:06:29.842486+09	아이브-리더	4
100	안유진 내용	대전 딸	2014-03-19 00:00:00+09	81	2025-12-31 16:06:46.704418+09	안유진-내용	4
1003	고민시 두번째	두번째	2025-12-28 15:38:31.737303+09	64	2025-12-31 16:08:08.273288+09	고민시-두번째	9
269	안유지 블러그입니다.	환영해요...	2013-06-19 00:00:00+09	81	2025-12-31 16:08:40.732442+09	안유지-블러그입니다	4
334	천천히	치고 나가면 안되요.	2012-10-02 00:00:00+09	9	2025-12-31 16:08:57.178684+09	천천히	1
16	업데이트	업데이트	2021-07-10 00:00:00+09	9	2025-12-31 16:17:55.005316+09	업데이트	5
331	이영웅 뭔 이름이 트로트가수 이름이야	테란에 이름에 맘에 안들음	2022-02-03 00:00:00+09	109	2025-12-31 16:18:11.984797+09	이영웅-뭔-이름이-트로트가수-이름이야	1
1002	고민시 블로그	처음이에요	2025-12-28 15:36:29.900186+09	64	2025-12-31 16:18:25.316932+09	고민시-블로그	9
1005	김윤중은 잘하나	왜 자동생성안되지	2025-12-28 18:08:58+09	137	2025-12-31 16:18:46.775965+09	김윤중은-잘하나	8
61	디파일러	조이기	2016-05-04 00:00:00+09	63	2025-12-31 16:19:35.984921+09	디파일러	8
94	이제동대 이재호	저그가 이겨야지	2015-06-02 00:00:00+09	1	2025-12-31 16:20:34.711717+09	이제동대-이재호	8
457	페이지에 검색 결과 변수를 이용해서 넣어주기	page_obj, is_paginated를 조건문으로..\r\n<pre>\r\n템플릿 내에서 변수 지정 방법\r\n{% with var_name=request.GET.searched|default="" var_name_2=request.GET.변수|default=""\r\n{% with param_1 = var_name|yesno:"&searched=,"|add: var_name  <br>\r\n   param_2=var_name_2|yesno:"&category=,"|add:var_name_2\r\n내용에 넣어줌\r\n&lt;a class="page-link" href="?page=1{{ search_param }}{{ category_param }}" aria-label="Previous">\r\n</pre>\r\n<h4>변수 안쓰면</h4>\r\n<pre>\r\n&lt;a class="page-link" href="?page=1&searched={{ request.GET.searched }}&category={{ request.GET.category }}" aria-label="Previous">\r\n</pre>\r\n이렇게 해야함	2011-06-04 00:00:00+09	141	2026-01-01 10:02:21.754868+09	페이지에-검색-결과-변수를-이용해서-넣어주기	5
383	Ama lur (Tierra Madre)	In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.\n\nAliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.\n\nSed ante. Vivamus tortor. Duis mattis egestas metus.	2009-11-07 00:00:00+09	109	2025-12-28 14:41:25.34567+09	\N	\N
386	Diary for Timothy, A	Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.\n\nMorbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.\n\nFusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.	2019-08-31 00:00:00+09	109	2025-12-28 14:41:25.34567+09	\N	\N
397	Smiley Face	Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.\n\nIn congue. Etiam justo. Etiam pretium iaculis justo.	2025-10-04 00:00:00+09	42	2025-12-28 14:41:25.34567+09	\N	\N
403	Flesh Gordon	Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.	2016-03-25 00:00:00+09	3	2025-12-28 14:41:25.34567+09	\N	\N
423	ListView	from django.views.generic import ListView, DetailView\r\n을 사용해서 페이지를 간단하게 볼수 있음	2025-03-09 00:00:00+09	1	2025-12-28 14:41:25.34567+09	\N	\N
439	Age of Heroes	Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.	2025-09-19 00:00:00+09	1	2025-12-28 14:41:25.34567+09	\N	\N
453	Norwegian Ninja	Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.\n\nDuis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.	2021-09-22 00:00:00+09	54	2025-12-28 14:41:25.34567+09	\N	\N
464	Brother (Brat)	Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.\n\nCurabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.\n\nPhasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.	2018-01-09 00:00:00+09	54	2025-12-28 14:41:25.34567+09	\N	\N
465	Me Too (Yo, también)	Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.\n\nQuisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.\n\nPhasellus in felis. Donec semper sapien a libero. Nam dui.	2019-08-04 00:00:00+09	12	2025-12-28 14:41:25.34567+09	\N	\N
478	Parker	Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.\n\nProin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.	2019-11-05 00:00:00+09	3	2025-12-28 14:41:25.34567+09	\N	\N
530	고민시가 적은 거에요	뭔짓을 해서 안나오지\r\nauthor 업데이트 하기	2014-12-13 00:00:00+09	3	2025-12-31 15:50:58.980728+09	고민시가-적은-거에요	4
355	사장남천동	정치 이슈....	2010-04-12 00:00:00+09	42	2025-12-31 15:51:30.532607+09	사장남천동	2
451	대통령실	미친 거임	2022-01-28 00:00:00+09	1	2025-12-31 16:05:47.109644+09	대통령실	6
356	Solt	졸리 나옴<br>\r\n영화<br>\r\n여러번 봄	2011-12-08 00:00:00+09	3	2025-12-31 23:03:18.833068+09	solt	9
377	쿠팡 이건 뭐 문제가 많아요	너무 문제가 많아요.	2017-09-05 00:00:00+09	2	2025-12-31 23:35:57.717073+09	쿠팡-이건-뭐-문제가-많아요	7
520	Queen	윤수철이 이겼네 축하	2012-01-06 00:00:00+09	12	2026-01-01 08:46:16.422723+09	queen	9
567	Coming Down the Mountain	Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.	2013-10-28 00:00:00+09	109	2025-12-28 14:41:25.34567+09	\N	\N
588	Stockholm Stories	Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.\n\nProin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.	2021-12-12 00:00:00+09	93	2025-12-28 14:41:25.34567+09	\N	\N
733	진서 알바감	10시에 출발	2015-08-14 00:00:00+09	1	2026-01-01 09:05:09.894981+09	진서-알바감	1
685	Gone Baby Gone	Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.\n\nProin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.	2017-09-27 00:00:00+09	109	2025-12-28 14:41:25.34567+09	\N	\N
729	We Are Marshall	Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.\n\nIn quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.\n\nMaecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.	2014-09-20 00:00:00+09	109	2025-12-28 14:41:25.34567+09	\N	\N
792	Death King, The (Der Todesking)	Sed ante. Vivamus tortor. Duis mattis egestas metus.	2015-05-31 00:00:00+09	1	2025-12-28 14:41:25.34567+09	\N	\N
593	눕기	변현제 승	2020-07-27 00:00:00+09	16	2025-12-31 15:53:01.634938+09	눕기	2
850	블로그 페이지는 ...	가능하면 class view로 구성함	2025-04-18 00:00:00+09	63	2025-12-28 14:41:25.34567+09	\N	\N
835	Year of the Gun	Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.\n\nNam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.\n\nCurabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.	2020-11-09 00:00:00+09	42	2025-12-28 14:41:25.34567+09	\N	\N
634	카타고리에 none 추가하기	get_context_data\r\n\r\ncategory_list = list(Category.objects.all().values('name')) 리스트로 생성<br>\r\n[{'name': '카테고리1'}, {'name': '카테고리2'}, ...]\r\n\r\ncount 추가 <br>\r\nfor c in category_list:\r\n  c['count'] = Post.objects.filter(category__name=c['name'].count()\r\n\r\ncategory_list 형태 : [ { 'name': name, 'count': count }, ... ]\r\nnone_count = Post.objects.filter(category__isnull=True).count()\r\ncategory_list.append({'name':'미분류', 'count': none_count })\r\n\r\ncontext['category_list'] = category_list	2025-02-18 00:00:00+09	2	2026-01-01 09:36:15.903626+09	카타고리에-none-추가하기	5
772	model view에서 공통 변수 지정	공통 변수 지정 방법\r\n\r\ndef setup(self, request, *args, **kwargs):\r\n        super().setup(request, *args, **kwargs)\r\n        self.get_category = request.GET.get('category')\r\n<br>\r\n<h3>사용은 self.get_category로 해서 사용</h3>	2012-05-07 00:00:00+09	81	2026-01-01 09:44:05.762862+09	model-view에서-공통-변수-지정	5
722	팅크	살작만 가볼까	2016-05-22 00:00:00+09	16	2025-12-31 23:55:12.539716+09	bratz-the-movie	9
550	templete에 html tag를 넣으면 layout 깨짐(enter후 2번째 줄에 넣어주면 OK)	template에 |safe 해주고\r\n\r\n내용에 html tag를 넣으면 화면 layout이 깨지는 현상 발생\r\n\r\n<br>\r\n<h1>중간 h1 tag</h1>\r\n중간에 넣은 tag를 영향이 없음	2019-10-27 00:00:00+09	81	2026-01-01 09:58:08.519594+09	templete에-html-tag를-넣으면-layout-깨짐	5
947	Alien Abduction	Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.	2023-10-19 00:00:00+09	109	2025-12-28 14:41:25.34567+09	\N	\N
950	Dinner with Friends	Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.\n\nVestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.\n\nDuis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.	2014-01-18 00:00:00+09	12	2025-12-28 14:41:25.34567+09	\N	\N
999	Scribbler, The	Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.\n\nPellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.	2014-07-21 00:00:00+09	109	2025-12-28 14:41:25.34567+09	\N	\N
981	대통령 직접해명하고....	단절의 의사를 표명해야 한다.\r\n이건 아니지\r\n완벽하게 국민의 승인을 받는 것은 힘들지	2016-01-07 00:00:00+09	63	2025-12-31 15:48:44.448583+09	대통령-직접해명하고	6
1004	나의 포스트	양식을 내가 만든 것임\r\ncrispy 사용하지 않음	2025-12-28 17:36:25.833987+09	2	2025-12-31 15:51:13.465584+09	나의-포스트	3
1006	폴스타 이영한 김지성	이영한은 좀 못하지	2025-12-29 12:54:59.948121+09	64	2025-12-31 15:52:47.245366+09	폴스타-이영한-김지성	8
916	html 내용추가 하면 전체 layout이 깨짐	html 내용추가 하면 전체 layout이 깨짐	2013-02-07 00:00:00+09	16	2025-12-31 16:09:16.088711+09	html-내용추가	5
\.


--
-- TOC entry 5098 (class 0 OID 0)
-- Dependencies: 235
-- Name: blog_post_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.blog_post_id_seq', 1006, true);


--
-- TOC entry 4941 (class 2606 OID 77949)
-- Name: blog_post blog_post_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.blog_post
    ADD CONSTRAINT blog_post_pkey PRIMARY KEY (id);


--
-- TOC entry 4938 (class 1259 OID 78281)
-- Name: blog_post_author_id_dd7a8485; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX blog_post_author_id_dd7a8485 ON public.blog_post USING btree (author_id);


--
-- TOC entry 4939 (class 1259 OID 78967)
-- Name: blog_post_category_id_c326dbf8; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX blog_post_category_id_c326dbf8 ON public.blog_post USING btree (category_id);


--
-- TOC entry 4942 (class 1259 OID 78901)
-- Name: blog_post_title_tag_dd70e627; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX blog_post_title_tag_dd70e627 ON public.blog_post USING btree (title_tag);


--
-- TOC entry 4943 (class 1259 OID 78902)
-- Name: blog_post_title_tag_dd70e627_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX blog_post_title_tag_dd70e627_like ON public.blog_post USING btree (title_tag varchar_pattern_ops);


--
-- TOC entry 4944 (class 2606 OID 78282)
-- Name: blog_post blog_post_author_id_dd7a8485_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.blog_post
    ADD CONSTRAINT blog_post_author_id_dd7a8485_fk_auth_user_id FOREIGN KEY (author_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4945 (class 2606 OID 78962)
-- Name: blog_post blog_post_category_id_c326dbf8_fk_blog_category_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.blog_post
    ADD CONSTRAINT blog_post_category_id_c326dbf8_fk_blog_category_id FOREIGN KEY (category_id) REFERENCES public.blog_category(id) DEFERRABLE INITIALLY DEFERRED;


-- Completed on 2026-01-01 10:27:37

--
-- PostgreSQL database dump complete
--

\unrestrict Ta5Kj6NURYEF0chFrSvACaQPvtlue0skWS5M8uG1W6XWFlOyRresmkXAhNmuj3K

