insert into events_event (id, name, event_date, manager_id, description, venue_id) values (2, 'Often', '2025-03-14', 15, 'Space-saving colander for rinsing fruits and vegetables.', 17);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (3, 'Weekly', '2025-08-25', 21, 'Compact blender that comes with travel cups for smoothies.', 17);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (4, 'Never', '2025-10-01', 17, 'Stylish and modern holder for storing wine bottles on walls.', 26);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (5, 'Never', '2025-04-06', 1, 'Quick oatmeal packets infused with apple and cinnamon, perfect for breakfast.', 18);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (6, 'Yearly', '2025-08-13', 26, 'Fun instruments to introduce kids to music.', 11);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (7, 'Weekly', '2025-08-01', 1, 'Functional leggings designed for maximum comfort during workouts.', 5);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (8, 'Daily', '2025-04-28', 2, 'High-quality whey protein powder for muscle recovery.', 23);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (9, 'Daily', '2025-05-29', 1, 'Juicy chicken breast stuffed with spinach and feta cheese, seasoned to perfection.', 28);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (10, 'Weekly', '2025-03-09', 11, 'Add a pop of color with this stylish patterned knit scarf.', 48);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (11, 'Daily', '2025-12-08', 30, 'Plain white rice, a staple for any meal.', 3);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (12, 'Monthly', '2025-07-01', 22, 'Fresh organic sweet potatoes, great for roasting or mashing.', 19);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (13, 'Daily', '2025-11-27', 19, 'Compact digital camera with 20MP resolution.', 35);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (14, 'Daily', '2025-07-08', 17, 'A blend of mixed nuts for snacking.', 10);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (15, 'Weekly', '2025-05-24', 7, 'Soft and cozy slippers for indoor wear.', 7);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (16, 'Yearly', '2025-11-16', 24, 'Complete kit for growing herbs indoors.', 15);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (17, 'Monthly', '2025-10-02', 3, 'Nutritious bars packed with protein for energy', 18);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (18, 'Often', '2025-01-24', 29, 'Mixed fresh vegetables for stir-frying or roasting.', 50);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (19, 'Yearly', '2025-10-15', 30, 'Eco-friendly bags for storing food without plastic waste.', 19);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (20, 'Yearly', '2025-07-23', 12, 'Set of decorative cushion covers for home decor.', 29);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (21, 'Never', '2025-09-15', 4, 'High-quality matcha powder for smoothies and baking.', 2);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (22, 'Weekly', '2025-09-19', 3, 'High-quality whole wheat flour for baking and cooking.', 8);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (23, 'Often', '2025-04-04', 26, 'Crispy sweet potato fries, perfectly seasoned and baked to perfection.', 45);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (24, 'Weekly', '2025-09-25', 26, 'Delicious veggie burger patties for grilling or frying.', 12);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (25, 'Daily', '2025-10-23', 16, 'Tender ribs smothered in a honey barbecue sauce.', 34);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (26, 'Yearly', '2025-03-19', 14, 'Variety pack of craft supplies for kids'' projects.', 49);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (27, 'Weekly', '2025-02-20', 8, 'Grilled chicken skewers glazed with teriyaki sauce.', 12);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (28, 'Weekly', '2025-01-09', 25, 'Comfortable eye mask that includes noise-canceling ear plugs.', 13);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (29, 'Weekly', '2025-10-03', 20, 'Ultrasonic essential oil diffuser with LED lights.', 46);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (30, 'Monthly', '2025-05-24', 9, 'Beginner-friendly drone with HD camera.', 32);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (31, 'Seldom', '2025-10-11', 26, 'Juicy pork tenderloin, great for roasting.', 15);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (32, 'Seldom', '2025-09-24', 16, 'Color-changing LED lights for home decoration with remote.', 12);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (33, 'Daily', '2025-12-11', 11, 'Delicious canned pineapple rings for desserts or salads.', 32);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (34, 'Seldom', '2025-07-22', 13, 'Insulated pitcher to keep beverages cold or hot.', 3);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (35, 'Weekly', '2025-08-18', 11, 'Flavorful chicken sausage, low in fat and fully cooked.', 21);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (36, 'Yearly', '2025-06-24', 6, 'Fresh button mushrooms, great for cooking.', 14);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (37, 'Daily', '2025-06-30', 17, 'Oats and honey bars with a chewy texture and nutty flavor.', 11);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (38, 'Daily', '2025-08-02', 21, 'Functional leggings designed for maximum comfort during workouts.', 21);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (39, 'Often', '2025-06-17', 18, 'A mix of fresh vegetables for quick stir-fries.', 45);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (40, 'Once', '2025-07-31', 16, 'Compact digital camera with 20MP resolution.', 11);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (41, 'Once', '2025-02-02', 8, 'A zesty seasoning for meats and vegetables', 35);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (42, 'Weekly', '2025-09-14', 24, 'Sweet peach halves packed in juice, great for desserts.', 22);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (43, 'Yearly', '2025-09-28', 30, 'Complete outdoor kit for camping and hiking.', 14);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (44, 'Weekly', '2025-01-04', 6, 'Instant oatmeal flavored with cranberries and orange zest for breakfast.', 28);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (45, 'Often', '2025-11-21', 13, 'Beautifully crafted jewelry box with compartments for storage.', 31);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (46, 'Once', '2025-03-31', 28, 'Zesty seasoning great for tacos and grilling.', 17);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (47, 'Often', '2025-12-03', 1, 'Creamy yogurt made from coconut milk, dairy-free and delicious.', 7);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (48, 'Yearly', '2025-02-13', 15, 'Chewy bars made with peanut butter and chocolate chips.', 23);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (49, 'Often', '2025-02-05', 9, 'Bright LED flashlight with adjustable beam.', 27);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (50, 'Weekly', '2025-01-28', 2, 'Rich and creamy dressing with garlic flavor, perfect for salads.', 34);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (51, 'Weekly', '2025-04-06', 7, 'Gluten-free pasta made from red lentils, packed with protein.', 19);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (52, 'Never', '2025-04-30', 22, 'A sweet and spicy sauce for dipping or cooking.', 14);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (53, 'Daily', '2025-11-20', 21, 'Finely ground flour from dried coconut meat.', 3);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (54, 'Seldom', '2025-11-12', 22, 'Upgrade your phone photography with this lens kit that includes wide-angle and macro lenses.', 25);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (55, 'Once', '2025-05-25', 29, 'Crispy fries tossed in truffle oil and parmesan, a gourmet snack.', 20);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (56, 'Daily', '2025-04-01', 22, 'Spicy and flavorful curry paste for authentic Thai dishes.', 29);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (57, 'Seldom', '2025-06-14', 16, 'Love-themed molds for creating desserts and treats.', 32);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (58, 'Monthly', '2025-03-08', 7, 'Lightly salted frozen edamame, a protein-packed snack.', 16);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (59, 'Seldom', '2025-11-17', 1, 'Rotating spice rack with 20 spice jars.', 24);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (60, 'Daily', '2025-04-16', 5, 'A fashion-forward bomber jacket to elevate your casual looks.', 21);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (61, 'Weekly', '2025-01-01', 12, 'A delightful mix of chocolate, coconut, and almonds in a snack bar.', 5);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (62, 'Monthly', '2025-01-13', 19, 'Eco-friendly yoga mat made from sustainable materials.', 34);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (63, 'Daily', '2025-08-03', 1, 'Durable toy designed for heavy chewers.', 45);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (64, 'Yearly', '2025-07-07', 1, 'Bell peppers stuffed with rice, beans, and spices, ready to bake.', 13);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (65, 'Weekly', '2025-03-30', 24, 'Lightweight hammock with a sturdy stand for relaxation anywhere.', 6);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (66, 'Yearly', '2025-08-04', 24, 'GPS collar that monitors your pet''s location and activity level.', 18);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (67, 'Monthly', '2025-11-21', 1, 'Cute fairy figurines to decorate your garden or potted plants.', 5);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (68, 'Never', '2025-03-30', 3, 'Mix to create a delicious chia seed pudding in just a few minutes.', 38);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (69, 'Daily', '2025-03-27', 25, 'Windshield sunshade for car interior protection.', 2);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (70, 'Weekly', '2025-04-20', 9, 'Fresh and tart organic green apples, great for snacking or baking.', 34);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (71, 'Weekly', '2025-06-20', 28, 'Cozy throw blanket perfect for adding warmth to your home.', 16);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (72, 'Daily', '2025-11-02', 9, 'Chic wrap jumpsuit that flatters the body and is perfect for any occasion.', 12);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (73, 'Seldom', '2025-10-13', 4, 'Tender grilled chicken marinated in lemon herbs.', 19);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (74, 'Once', '2025-09-21', 11, 'Variety pack of sticky notes in different colors and sizes.', 49);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (75, 'Never', '2025-03-20', 19, 'Moist and flavorful muffins packed with fall spices and pumpkin puree.', 46);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (76, 'Never', '2025-09-02', 24, 'Safe and easy-to-use nail clippers for pets.', 11);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (77, 'Often', '2025-04-27', 8, 'Waterproof camera for capturing underwater adventures.', 4);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (78, 'Seldom', '2025-11-03', 11, 'Delicious cookies with rich chocolate flavor and a hint of mint.', 50);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (79, 'Daily', '2025-11-08', 12, 'A fresh, flavorful basil pesto for pasta and more', 21);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (80, 'Seldom', '2025-09-03', 12, 'Savory quiche loaded with spinach and cheese.', 16);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (81, 'Yearly', '2025-09-02', 3, 'Convenient electric screwdriver for DIY projects at home.', 48);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (82, 'Daily', '2025-01-07', 6, 'Eco-friendly power bank that charges via sunlight.', 39);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (83, 'Weekly', '2025-07-12', 16, 'A sweet and spicy sauce ideal for spring rolls or chicken nuggets.', 1);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (84, 'Once', '2025-05-01', 3, 'Flavorful rice mixed with coconut and lime, a tropical side dish.', 45);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (85, 'Daily', '2025-12-20', 21, 'Lightweight tennis racket for beginners and advanced players.', 6);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (86, 'Monthly', '2025-04-21', 4, 'Crispy sweet potato bites, delicious as a side or snack.', 16);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (87, 'Once', '2025-03-14', 20, 'Inspiring cookbook with healthy recipes.', 14);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (88, 'Weekly', '2025-08-16', 6, 'Essential attachments for pressure washing.', 1);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (89, 'Yearly', '2025-08-08', 11, 'Instant pressure cooker with multiple cooking settings.', 26);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (90, 'Daily', '2025-10-13', 29, 'Flavorful sauce perfect for stir-frying vegetables and tofu.', 16);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (91, 'Seldom', '2025-01-28', 28, 'Set of whisks in various sizes for cooking.', 25);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (92, 'Seldom', '2025-01-08', 7, 'A convenient powder mix combining greens and fruits for smoothies.', 6);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (93, 'Never', '2025-02-19', 26, 'Delicious vegetable dumplings, perfect for steaming or frying.', 13);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (94, 'Weekly', '2025-04-28', 1, 'A flavorful spread made with roasted garlic and creamy butter.', 47);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (95, 'Weekly', '2025-09-01', 17, 'Freshly cut carrot sticks, perfect for snacking.', 4);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (96, 'Daily', '2025-06-24', 13, 'All-in-one kit for making delicious chicken salad.', 16);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (97, 'Yearly', '2025-01-11', 4, 'A delicious sauce perfect for stir-frying or glazing meats.', 6);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (98, 'Yearly', '2025-07-18', 3, 'Set of resistance bands for strength training at home.', 12);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (99, 'Monthly', '2025-02-23', 22, 'Spicy and flavorful curry paste for authentic Thai dishes.', 13);
insert into events_event (id, name, event_date, manager_id, description, venue_id) values (100, 'Seldom', '2025-09-07', 8, 'Genuine leather wallet with multiple compartments.', 1);
