INSERT INTO library_genre (name) VALUES
('Fiction'),
('Crime Fiction'),
('Science Fiction'),
('Historical Fiction'),
('Literary Fiction'),
('Non-Fiction'),
('Mystery'),
('Action & Adventure'),
('Business'), 
('Drama'), 
('Fantasy'), 
('Horror'),
('Romance'),
('Mystery'),
('Thriller'),
('Classics'),
('Non-fiction'),
('Young Adult'),
('Self-Help'),
('Memoir'),
('Autobiography'),
('Computer Programming'),
('language'),
('travel'),
('cooking'),
('universe'),
('econology');


