# Generated by Django 5.2.8 on 2025-12-09 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('web', 'Web Server'), ('was', 'Web Application Server'), ('db', 'Database Server'), ('api', 'API Server'), ('mgmt', 'Management Server'), ('cache', 'Cache Server'), ('proxy', 'Proxy Server'), ('other', 'Other')], default='other', max_length=50)),
                ('role_version', models.CharField(max_length=255)),
                ('is_virtual', models.BooleanField(default=False)),
                ('is_master', models.BooleanField(default=False)),
                ('ip_real', models.GenericIPAddressField()),
                ('ip_management', models.GenericIPAddressField(blank=True, null=True)),
                ('ip_virtual', models.GenericIPAddressField(blank=True, null=True)),
                ('os', models.CharField(max_length=255)),
                ('kernel', models.CharField(max_length=255)),
                ('cpu_core_count', models.IntegerField()),
                ('total_memory', models.IntegerField()),
                ('total_disk', models.IntegerField()),
                ('uptime', models.IntegerField()),
                ('checked_at', models.DateTimeField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(null=True)),
                ('is_confirmed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network_local_1', models.CharField(choices=[('100M', '100M'), ('1G', '1G'), ('10G', '10G'), ('40G', '40G'), ('100G', '100G'), ('8G', '8G FC'), ('16G', '16G FC'), ('32G', '32G FC'), ('64G', '64G FC')], default='10G', max_length=10)),
                ('network_local_1_inbound', models.DecimalField(decimal_places=2, max_digits=20)),
                ('network_local_1_outbound', models.DecimalField(decimal_places=2, max_digits=20)),
                ('network_local_2', models.CharField(blank=True, choices=[('100M', '100M'), ('1G', '1G'), ('10G', '10G'), ('40G', '40G'), ('100G', '100G'), ('8G', '8G FC'), ('16G', '16G FC'), ('32G', '32G FC'), ('64G', '64G FC')], default='10G', max_length=10, null=True)),
                ('network_local_2_inbound', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('network_local_2_outbound', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('network_nas_1', models.CharField(blank=True, choices=[('100M', '100M'), ('1G', '1G'), ('10G', '10G'), ('40G', '40G'), ('100G', '100G'), ('8G', '8G FC'), ('16G', '16G FC'), ('32G', '32G FC'), ('64G', '64G FC')], default='10G', max_length=10, null=True)),
                ('network_nas_1_inbound', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('network_nas_1_outbound', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('network_nas_2', models.CharField(blank=True, choices=[('100M', '100M'), ('1G', '1G'), ('10G', '10G'), ('40G', '40G'), ('100G', '100G'), ('8G', '8G FC'), ('16G', '16G FC'), ('32G', '32G FC'), ('64G', '64G FC')], default='10G', max_length=10, null=True)),
                ('network_nas_2_inbound', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('network_nas_2_outbound', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('network_san_1', models.CharField(blank=True, choices=[('100M', '100M'), ('1G', '1G'), ('10G', '10G'), ('40G', '40G'), ('100G', '100G'), ('8G', '8G FC'), ('16G', '16G FC'), ('32G', '32G FC'), ('64G', '64G FC')], default='16G', max_length=10, null=True)),
                ('network_san_1_inbound', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('network_san_1_outbound', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('network_san_2', models.CharField(blank=True, choices=[('100M', '100M'), ('1G', '1G'), ('10G', '10G'), ('40G', '40G'), ('100G', '100G'), ('8G', '8G FC'), ('16G', '16G FC'), ('32G', '32G FC'), ('64G', '64G FC')], default='16G', max_length=10, null=True)),
                ('network_san_2_inbound', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('network_san_2_outbound', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('network_mgmt_1', models.CharField(choices=[('100M', '100M'), ('1G', '1G'), ('10G', '10G'), ('40G', '40G'), ('100G', '100G'), ('8G', '8G FC'), ('16G', '16G FC'), ('32G', '32G FC'), ('64G', '64G FC')], default='1G', max_length=20)),
                ('network_mgmt_2', models.CharField(blank=True, choices=[('100M', '100M'), ('1G', '1G'), ('10G', '10G'), ('40G', '40G'), ('100G', '100G'), ('8G', '8G FC'), ('16G', '16G FC'), ('32G', '32G FC'), ('64G', '64G FC')], default='1G', max_length=20, null=True)),
                ('checked_at', models.DateTimeField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(null=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('server', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='asct.serverinfo')),
            ],
        ),
        migrations.CreateModel(
            name='MemoryUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_percent', models.DecimalField(decimal_places=2, max_digits=4)),
                ('checked_at', models.DateTimeField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(null=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('server', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='asct.serverinfo')),
            ],
        ),
        migrations.CreateModel(
            name='DiskUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_local_total', models.IntegerField()),
                ('storage_local_usage_percent', models.DecimalField(decimal_places=2, max_digits=4)),
                ('storage_san_total', models.IntegerField(blank=True, null=True)),
                ('storage_san_usage_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('storage_nfs_total', models.IntegerField(blank=True, null=True)),
                ('storage_nfs_usage_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('checked_at', models.DateTimeField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(null=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('server', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='asct.serverinfo')),
            ],
        ),
        migrations.CreateModel(
            name='CPUUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_percent', models.DecimalField(decimal_places=2, max_digits=4)),
                ('checked_at', models.DateTimeField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(null=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('server', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='asct.serverinfo')),
            ],
        ),
        migrations.CreateModel(
            name='SSHInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_id', models.CharField(max_length=20)),
                ('ip', models.GenericIPAddressField()),
                ('port', models.IntegerField(default=22)),
                ('password', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='serverinfo',
            name='sshinfo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='asct.sshinfo'),
        ),
        migrations.CreateModel(
            name='SysctlSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('checked_at', models.DateTimeField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(null=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asct.serverinfo')),
            ],
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_level', models.CharField(choices=[('DEBUG', 'DEBUG'), ('INFO', 'INFO'), ('WARNING', 'WARNING'), ('ERROR', 'ERROR'), ('CRITICAL', 'CRITICAL')], default='ERROR', max_length=10)),
                ('message', models.TextField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(null=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asct.serverinfo')),
            ],
        ),
    ]
