# Generated by Django 5.2.8 on 2025-12-13 04:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SSHInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_id', models.CharField(max_length=20)),
                ('ip', models.GenericIPAddressField()),
                ('port', models.IntegerField(default=22)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('web', 'Web Server'), ('was', 'Web Application Server'), ('db', 'Database Server'), ('api', 'API Server'), ('mgmt', 'Management Server'), ('cache', 'Cache Server'), ('proxy', 'Proxy Server'), ('other', 'Other')], default='other', max_length=10)),
                ('role_version', models.CharField(max_length=255)),
                ('ip_real', models.GenericIPAddressField()),
                ('os', models.CharField(max_length=255)),
                ('kernel', models.CharField(max_length=255)),
                ('cpu_core_count', models.IntegerField()),
                ('total_memory', models.IntegerField()),
                ('total_disk', models.IntegerField()),
                ('uptime', models.IntegerField()),
                ('is_virtual', models.BooleanField(default=True)),
                ('is_master', models.BooleanField(default=True)),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.TextField(null=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('sshinfo', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='asct.sshinfo')),
            ],
            options={
                'ordering': ['hostname', '-checked_at'],
                'unique_together': {('hostname', 'ip_real', 'checked_at')},
            },
        ),
        migrations.CreateModel(
            name='NetworkUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network_service', models.CharField(choices=[('100M', '100M'), ('1G', '1G'), ('10G', '10G'), ('40G', '40G'), ('100G', '100G'), ('8G', '8G FC'), ('16G', '16G FC'), ('32G', '32G FC'), ('64G', '64G FC')], default='10G', max_length=10)),
                ('network_service_inbound', models.DecimalField(decimal_places=2, max_digits=20)),
                ('network_service_outbound', models.DecimalField(decimal_places=2, max_digits=20)),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.TextField(blank=True, null=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asct.serverinfo')),
            ],
            options={
                'ordering': ['server__hostname', '-timestamp'],
                'unique_together': {('server', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='MemoryUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_percent', models.DecimalField(decimal_places=2, max_digits=4)),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.TextField(blank=True, null=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asct.serverinfo')),
            ],
            options={
                'ordering': ['server__hostname', '-timestamp'],
                'unique_together': {('server', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='DiskUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_local_total', models.IntegerField()),
                ('storage_local_usage_percent', models.DecimalField(decimal_places=2, max_digits=4)),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.TextField(blank=True, null=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asct.serverinfo')),
            ],
            options={
                'ordering': ['server__hostname', '-timestamp'],
                'unique_together': {('server', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='CPUUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_percent', models.DecimalField(decimal_places=2, max_digits=4)),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.TextField(blank=True, null=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asct.serverinfo')),
            ],
            options={
                'ordering': ['server__hostname', '-timestamp'],
                'unique_together': {('server', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='SysctlSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.TextField(blank=True, null=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asct.serverinfo')),
            ],
            options={
                'ordering': ['server', '-checked_at'],
                'unique_together': {('server', 'checked_at')},
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_level', models.CharField(choices=[('DEBUG', 'DEBUG'), ('INFO', 'INFO'), ('WARNING', 'WARNING'), ('ERROR', 'ERROR'), ('CRITICAL', 'CRITICAL')], default='ERROR', max_length=10)),
                ('log_message', models.TextField()),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.TextField(blank=True, null=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asct.serverinfo')),
            ],
            options={
                'ordering': ['server', '-checked_at'],
                'unique_together': {('server', 'checked_at')},
            },
        ),
    ]
