# Generated by Django 5.2.8 on 2025-12-13 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asct', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sshinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
