# Generated by Django 5.2.8 on 2025-12-13 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asct', '0002_alter_sshinfo_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='serverinfo',
            name='role',
        ),
        migrations.AddField(
            model_name='serverinfo',
            name='roles',
            field=models.ManyToManyField(blank=True, to='asct.role'),
        ),
    ]
